In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
This is a good data

SyntaxError: invalid syntax (Temp/ipykernel_9808/2598754109.py, line 1)

Data:
> static file: media prediction and its cost.csv
>> source: https://www.kaggle.com/datasets/ramjasmaurya/medias-cost-prediction-in-foodmart

In [2]:
data = pd.read_csv('media prediction and its cost.csv')
data.head(2)

,food_category,food_department,food_family,store_sales(in millions),store_cost(in millions),unit_sales(in millions),promotion_name,sales_country,marital_status,gender,...,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,media_type,cost
0,Breakfast Foods,Frozen Foods,Food,7.36,2.7232,4.0,Bag Stuffers,USA,M,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",126.62
1,Breakfast Foods,Frozen Foods,Food,5.52,2.5944,3.0,Cash Register Lottery,USA,M,M,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",59.86

In [10]:
list(data.columns),len(list(data.columns))

(['food_category',
  'food_department',
  'food_family',
  'store_sales(in millions)',
  'store_cost(in millions)',
  'unit_sales(in millions)',
  'promotion_name',
  'sales_country',
  'marital_status',
  'gender',
  'total_children',
  'education',
  'member_card',
  'occupation',
  'houseowner',
  'avg_cars_at home(approx)',
  'avg. yearly_income',
  'num_children_at_home',
  'avg_cars_at home(approx).1',
  'brand_name',
  'SRP',
  'gross_weight',
  'net_weight',
  'recyclable_package',
  'low_fat',
  'units_per_case',
  'store_type',
  'store_city',
  'store_state',
  'store_sqft',
  'grocery_sqft',
  'frozen_sqft',
  'meat_sqft',
  'coffee_bar',
  'video_store',
  'salad_bar',
  'prepared_food',
  'florist',
  'media_type',
  'cost'],
 40)

In [12]:
data.shape

(60428, 40)

In [13]:
top_view = pd.DataFrame()
for col in list(data.columns):
    
    datum = pd.DataFrame({'col_name':[col],
                          '#uniq_values':[data[col].nunique()],
                          'dtype_':[data[col].dtype],
                          'missing_':[data[col].isna().sum()]})
    top_view = pd.concat([top_view,datum],axis = 0)
    print(f".... analyzing column :{col}")

.... analyzing column :food_category
.... analyzing column :food_department
.... analyzing column :food_family
.... analyzing column :store_sales(in millions)
.... analyzing column :store_cost(in millions)
.... analyzing column :unit_sales(in millions)
.... analyzing column :promotion_name
.... analyzing column :sales_country
.... analyzing column :marital_status
.... analyzing column :gender
.... analyzing column :total_children
.... analyzing column :education
.... analyzing column :member_card
.... analyzing column :occupation
.... analyzing column :houseowner
.... analyzing column :avg_cars_at home(approx)
.... analyzing column :avg. yearly_income
.... analyzing column :num_children_at_home
.... analyzing column :avg_cars_at home(approx).1
.... analyzing column :brand_name
.... analyzing column :SRP
.... analyzing column :gross_weight
.... analyzing column :net_weight
.... analyzing column :recyclable_package
.... analyzing column :low_fat
.... analyzing column :units_per_case
.... analyzing column :store_type
.... analyzing column :store_city
.... analyzing column :store_state
.... analyzing column :store_sqft
.... analyzing column :grocery_sqft
.... analyzing column :frozen_sqft
.... analyzing column :meat_sqft
.... analyzing column :coffee_bar
.... analyzing column :video_store
.... analyzing column :salad_bar
.... analyzing column :prepared_food
.... analyzing column :florist
.... analyzing column :media_type
.... analyzing column :cost

In [14]:
top_view

                     col_name  #uniq_values   dtype_  missing_
0               food_category            45   object         0
0             food_department            22   object         0
0                 food_family             3   object         0
0    store_sales(in millions)          1033  float64         0
0     store_cost(in millions)          9919  float64         0
0     unit_sales(in millions)             6  float64         0
0              promotion_name            49   object         0
0               sales_country             3   object         0
0              marital_status             2   object         0
0                      gender             2   object         0
0              total_children             6  float64         0
0                   education             5   object         0
0                 member_card             4   object         0
0                  occupation             5   object         0
0                  houseowner             2   object         0
0    avg_cars_at home(approx)             5  float64         0
0          avg. yearly_income             8   object         0
0        num_children_at_home             6  float64         0
0  avg_cars_at home(approx).1             5  float64         0
0                  brand_name           111   object         0
0                         SRP           315  float64         0
0                gross_weight           376  float64         0
0                  net_weight           332  float64         0
0          recyclable_package             2  float64         0
0                     low_fat             2  float64         0
0              units_per_case            36  float64         0
0                  store_type             5   object         0
0                  store_city            19   object         0
0                 store_state            10   object         0
0                  store_sqft            20  float64         0
0                grocery_sqft            20  float64         0
0                 frozen_sqft            20  float64         0
0                   meat_sqft            20  float64         0
0                  coffee_bar             2  float64         0
0                 video_store             2  float64         0
0                   salad_bar             2  float64         0
0               prepared_food             2  float64         0
0                     florist             2  float64         0
0                  media_type            13   object         0
0                        cost           328  float64         0

In [20]:
numeric_cols = data.select_dtypes(include = 'number').columns.tolist()
categorical_cols = data.select_dtypes(include = 'object').columns.tolist()
print(f"number of numerical columns :{len(numeric_cols)}")
print(f"number of numerical columns :{len(categorical_cols)}")

number of numerical columns :23
number of numerical columns :17

In [25]:
numeric_cols[0:len(numeric_cols)-1]

['store_sales(in millions)',
 'store_cost(in millions)',
 'unit_sales(in millions)',
 'total_children',
 'avg_cars_at home(approx)',
 'num_children_at_home',
 'avg_cars_at home(approx).1',
 'SRP',
 'gross_weight',
 'net_weight',
 'recyclable_package',
 'low_fat',
 'units_per_case',
 'store_sqft',
 'grocery_sqft',
 'frozen_sqft',
 'meat_sqft',
 'coffee_bar',
 'video_store',
 'salad_bar',
 'prepared_food',
 'florist']

In [23]:
data[numeric_cols].corr()

,store_sales(in millions),store_cost(in millions),unit_sales(in millions),total_children,avg_cars_at home(approx),num_children_at_home,avg_cars_at home(approx).1,SRP,gross_weight,net_weight,...,store_sqft,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,cost
store_sales(in millions),1.000000,0.954685,0.503482,0.083313,0.004498,0.032437,0.004498,0.833478,0.036179,0.032014,...,0.015543,0.010442,0.017886,0.017883,-0.029368,0.019179,0.031459,0.031459,0.030603,-0.004621
store_cost(in millions),0.954685,1.000000,0.480087,0.079058,0.002865,0.027576,0.002865,0.795880,0.034237,0.030257,...,0.017877,0.012884,0.019245,0.019242,-0.027126,0.019252,0.033206,0.033206,0.030929,-0.004162
unit_sales(in millions),0.503482,0.480087,1.000000,0.163188,0.023667,0.066725,0.023667,-0.002358,0.001255,0.001137,...,0.031464,0.024857,0.030563,0.030557,-0.057633,0.034996,0.057878,0.057878,0.055885,-0.015015
total_children,0.083313,0.079058,0.163188,1.000000,0.098110,0.394709,0.098110,0.000545,-0.000186,0.000142,...,0.000555,0.018526,-0.026926,-0.026923,0.002836,-0.000591,-0.013764,-0.013764,-0.003361,-0.003900
avg_cars_at home(approx),0.004498,0.002865,0.023667,0.098110,1.000000,0.130841,1.000000,-0.007921,0.004588,0.004155,...,-0.015815,-0.017694,-0.007470,-0.007466,-0.002702,0.014001,-0.008982,-0.008982,-0.004138,0.011658
num_children_at_home,0.032437,0.027576,0.066725,0.394709,0.130841,1.000000,0.130841,-0.000477,-0.002480,-0.002535,...,0.006150,0.025008,-0.024624,-0.024617,-0.016873,-0.013750,-0.023680,-0.023680,-0.008918,-0.002549
avg_cars_at home(approx).1,0.004498,0.002865,0.023667,0.098110,1.000000,0.130841,1.000000,-0.007921,0.004588,0.004155,...,-0.015815,-0.017694,-0.007470,-0.007466,-0.002702,0.014001,-0.008982,-0.008982,-0.004138,0.011658
SRP,0.833478,0.795880,-0.002358,0.000545,-0.007921,-0.000477,-0.007921,1.000000,0.043332,0.038639,...,0.001663,-0.000505,0.004375,0.004374,-0.000014,0.002031,0.002811,0.002811,0.003998,0.002082
gross_weight,0.036179,0.034237,0.001255,-0.000186,0.004588,-0.002480,0.004588,0.043332,1.000000,0.988903,...,-0.005254,-0.004749,-0.004195,-0.004195,0.001933,0.002293,0.001944,0.001944,0.003109,0.001281
net_weight,0.032014,0.030257,0.001137,0.000142,0.004155,-0.002535,0.004155,0.038639,0.988903,1.000000,...,-0.004374,-0.003723,-0.003843,-0.003842,0.001816,0.002551,0.002656,0.002656,0.002579,0.001343
recyclable_package,0.034293,0.030213,0.001599,0.002794,0.003725,0.001380,0.003725,0.042013,0.052340,0.054580,...,0.001358,0.001562,0.000575,0.000574,-0.000844,0.001464,0.000758,0.000758,-0.001339,-0.001720
low_fat,-0.006134,-0.005976,-0.001129,-0.002824,-0.004312,-0.001818,-0.004312,-0.005527,-0.033883,-0.036211,...,0.001675,-0.002664,0.007682,0.007680,0.000897,-0.004470,0.002005,0.002005,0.002609,0.004207
units_per_case,-0.010630,-0.009792,0.000084,0.002307,-0.007265,0.000118,-0.007265,-0.011951,-0.011754,-0.014394,...,0.001947,0.003687,-0.001372,-0.001371,0.001782,0.002969,0.003144,0.003144,0.000520,-0.002776
store_sqft,0.015543,0.017877,0.031464,0.000555,-0.015815,0.006150,-0.015815,0.001663,-0.005254,-0.004374,...,1.000000,0.912864,0.784734,0.784768,-0.153842,-0.080342,0.404138,0.404138,-0.019559,-0.039656
grocery_sqft,0.010442,0.012884,0.024857,0.018526,-0.017694,0.025008,-0.017694,-0.000505,-0.004749,-0.003723,...,0.912864,1.000000,0.463301,0.463350,-0.234822,-0.104593,0.309247,0.309247,-0.125958,-0.025108
frozen_sqft,0.017886,0.019245,0.030563,-0.026926,-0.007470,-0.024624,-0.007470,0.004375,-0.004195,-0.003843,...,0.784734,0.463301,1.000000,1.000000,0.022573,-0.015571,0.407767,0.407767,0.148797,-0.047971
meat_sqft,0.017883,0.019242,0.030557,-0.026923,-0.007466,-0.024617,-0.007466,0.004374,-0.004195,-0.003842,...,0.784768,0.463350,1.000000,1.000000,0.022544,-0.015636,0.407736,0.407736,0.148729,-0.047962
coffee_bar,-0.029368,-0.027126,-0.057633,0.002836,-0.002702,-0.016873,-0.002702,-0.000014,0.001933,0.001816,...,-0.153842,-0.234822,0.022573,0.022544,1.000000,0.588821,0.530764,0.530764,0.630623,-0.060859
video_store,0.019179,0.019252,0.034996,-0.000591,0.014001,-0.013750,0.014001,0.002031,0.002293,0.002551,...,-0.080342,-0.104593,-0.015571,-0.015636,0.588821,1.000000,0.619918,0.619918,0.652937,-0.111214
salad_bar,0.031459,0.033206,0.057878,-0.013764,-0.008982,-0.023680,-0.008982,0.002811,0.001944,0.002656,...,0.404138,0.309247,0.407767,0.407736,0.530764,0.619918,1.000000,1.000000,0.641725,-0.095596
prepared_food,0.031459,0.033206,0.057878,-0.013764,-0.008982,-0.023680,-0.008982,0.002811,0.001944,0.002656,...,0.404138,0.309247,0.407767,0.407736,0.530764,0.619918,1.000000,1.000000,0.641725,-0.095596
florist,0.030603,0.030929,0.055885,-0.003361,-0.004138,-0.008918,-0.004138,0.003998,0.003109,0.002579,...,-0.019559,-0.125958,0.148797,0.148729,0.630623,0.652937,0.641725,0.641725,1.000000,-0.087340
cost,-0.004621,-0.004162,-0.015015,-0.003900,0.011658,-0.002549,0.011658,0.002082,0.001281,0.001343,...,-0.039656,-0.025108,-0.047971,-0.047962,-0.060859,-0.111214,-0.095596,-0.095596,-0.087340,1.000000

In [41]:
corr_study = pd.DataFrame()
for col in numeric_cols[0:len(numeric_cols)-1]:
    datum = pd.DataFrame({'col_name':[col],
                          'with_cost':['cost'],
                          'correlation':[data[col].corr(data['cost'])]})
    corr_study = pd.concat([corr_study,datum])
corr_study

                     col_name with_cost  correlation
0    store_sales(in millions)      cost    -0.004621
0     store_cost(in millions)      cost    -0.004162
0     unit_sales(in millions)      cost    -0.015015
0              total_children      cost    -0.003900
0    avg_cars_at home(approx)      cost     0.011658
0        num_children_at_home      cost    -0.002549
0  avg_cars_at home(approx).1      cost     0.011658
0                         SRP      cost     0.002082
0                gross_weight      cost     0.001281
0                  net_weight      cost     0.001343
0          recyclable_package      cost    -0.001720
0                     low_fat      cost     0.004207
0              units_per_case      cost    -0.002776
0                  store_sqft      cost    -0.039656
0                grocery_sqft      cost    -0.025108
0                 frozen_sqft      cost    -0.047971
0                   meat_sqft      cost    -0.047962
0                  coffee_bar      cost    -0.060859
0                 video_store      cost    -0.111214
0                   salad_bar      cost    -0.095596
0               prepared_food      cost    -0.095596
0                     florist      cost    -0.087340

In [40]:
def corr_between(data,col_name_x,col_name_y):
    corr = data[col_name_x].corr(data[col_name_y])
    return corr

corr_between(data,'store_sales(in millions)','avg_cars_at home(approx)')

0.004497637307076714

Food Family Analysis:

In [42]:
categorical_cols

['food_category',
 'food_department',
 'food_family',
 'promotion_name',
 'sales_country',
 'marital_status',
 'gender',
 'education',
 'member_card',
 'occupation',
 'houseowner',
 'avg. yearly_income',
 'brand_name',
 'store_type',
 'store_city',
 'store_state',
 'media_type']

In [45]:
numeric_cols

['store_sales(in millions)',
 'store_cost(in millions)',
 'unit_sales(in millions)',
 'total_children',
 'avg_cars_at home(approx)',
 'num_children_at_home',
 'avg_cars_at home(approx).1',
 'SRP',
 'gross_weight',
 'net_weight',
 'recyclable_package',
 'low_fat',
 'units_per_case',
 'store_sqft',
 'grocery_sqft',
 'frozen_sqft',
 'meat_sqft',
 'coffee_bar',
 'video_store',
 'salad_bar',
 'prepared_food',
 'florist',
 'cost']

In [44]:
data.groupby('food_family').agg(food_depts = pd.NamedAgg('food_department','count'),
                                food_categories = pd.NamedAgg('food_category','count')).reset_index()

      food_family  food_depts  food_categories
0           Drink        5571             5571
1            Food       43284            43284
2  Non-Consumable       11573            11573

In [55]:
dat_foodfamily = data.groupby('food_family').agg(food_depts = pd.NamedAgg('food_department','count'),
                                food_categories = pd.NamedAgg('food_category','count'),
                                totalstore_sales = pd.NamedAgg('store_sales(in millions)','sum'),
                                total_store_cost = pd.NamedAgg('store_cost(in millions)','sum'),
                                totalunits_sold = pd.NamedAgg('unit_sales(in millions)','sum')).reset_index()
dat_foodfamily

,food_family,food_depts,food_categories,totalstore_sales,total_store_cost,totalunits_sold
0,Drink,5571,5571,34178.40,13668.1469,17299.0
1,Food,43284,43284,284614.54,113970.3556,133901.0
2,Non-Consumable,11573,11573,76468.46,30650.1962,35714.0

In [56]:
dat_fooddept = data.groupby(['food_family','food_department']).agg(food_categories = pd.NamedAgg('food_category','count'),
                                totalstore_sales = pd.NamedAgg('store_sales(in millions)','sum'),
                                total_store_cost = pd.NamedAgg('store_cost(in millions)','sum'),
                                totalunits_sold = pd.NamedAgg('unit_sales(in millions)','sum')).reset_index()
dat_fooddept

,food_family,food_department,food_categories,totalstore_sales,total_store_cost,totalunits_sold
0,Drink,Alcoholic Beverages,1590,10096.61,4048.5488,4951.0
1,Drink,Beverages,3014,19003.40,7591.0691,9324.0
2,Drink,Dairy,967,5078.39,2028.5290,3024.0
3,Food,Baked Goods,1797,11813.05,4728.0011,5552.0
4,Food,Baking Goods,4497,26714.37,10655.7569,13868.0
5,Food,Breakfast Foods,778,5049.56,2024.9536,2415.0
6,Food,Canned Foods,4238,27085.84,10876.5089,13079.0
7,Food,Canned Products,400,2271.88,916.7888,1243.0
8,Food,Dairy,2868,20626.94,8307.3254,8801.0
9,Food,Deli,2787,18068.32,7217.5224,8638.0
10,Food,Eggs,952,6398.62,2558.0635,2926.0
11,Food,Frozen Foods,6126,39055.11,15647.3022,18909.0
12,Food,Meat,385,2486.86,984.3473,1199.0
13,Food,Produce,8521,56914.58,22787.2701,26361.0
14,Food,Seafood,375,2470.42,984.0403,1164.0
15,Food,Snack Foods,6919,47726.96,19115.3878,21491.0
16,Food,Snacks,1538,10141.97,4056.9256,4822.0
17,Food,Starchy Foods,1103,7790.06,3110.1617,3433.0
18,Non-Consumable,Carousel,225,1300.86,523.1877,697.0
19,Non-Consumable,Checkout,385,2519.88,1015.8886,1205.0
20,Non-Consumable,Health and Hygiene,3807,23860.63,9577.4205,11767.0
21,Non-Consumable,Household,6185,42579.56,17043.4544,19089.0
22,Non-Consumable,Periodicals,971,6207.53,2490.2450,2956.0

In [57]:
dat_foodcat = data.groupby(['food_family','food_department','food_category']).agg(totalstore_sales = pd.NamedAgg('store_sales(in millions)','sum'),
                                total_store_cost = pd.NamedAgg('store_cost(in millions)','sum'),
                                totalunits_sold = pd.NamedAgg('unit_sales(in millions)','sum')).reset_index()
dat_foodcat

,food_family,food_department,food_category,totalstore_sales,total_store_cost,totalunits_sold
0,Drink,Alcoholic Beverages,Beer and Wine,10096.61,4048.5488,4951.0
1,Drink,Beverages,Carbonated Beverages,4467.83,1773.1219,2427.0
2,Drink,Beverages,Drinks,4220.94,1692.8374,1792.0
3,Drink,Beverages,Hot Beverages,5856.23,2342.0334,2750.0
4,Drink,Beverages,Pure Juice Beverages,4458.40,1783.0764,2355.0
5,Drink,Dairy,Dairy,5078.39,2028.5290,3024.0
6,Food,Baked Goods,Bread,11813.05,4728.0011,5552.0
7,Food,Baking Goods,Baking Goods,11313.59,4523.1481,6037.0
8,Food,Baking Goods,Jams and Jellies,15400.78,6132.6088,7831.0
9,Food,Breakfast Foods,Breakfast Foods,5049.56,2024.9536,2415.0
10,Food,Canned Foods,Canned Anchovies,1664.65,672.6467,660.0
11,Food,Canned Foods,Canned Clams,1274.46,497.0866,630.0
12,Food,Canned Foods,Canned Oysters,1165.60,465.5039,568.0
13,Food,Canned Foods,Canned Sardines,868.28,345.6828,534.0
14,Food,Canned Foods,Canned Shrimp,1448.43,598.6557,553.0
15,Food,Canned Foods,Canned Soup,10419.14,4190.5216,5317.0
16,Food,Canned Foods,Canned Tuna,2320.84,925.1180,1207.0
17,Food,Canned Foods,Vegetables,7924.44,3181.2936,3610.0
18,Food,Canned Products,Fruit,2271.88,916.7888,1243.0
19,Food,Dairy,Dairy,20626.94,8307.3254,8801.0
20,Food,Deli,Meat,14710.30,5865.9227,6772.0
21,Food,Deli,Side Dishes,3358.02,1351.5997,1866.0
22,Food,Eggs,Eggs,6398.62,2558.0635,2926.0
23,Food,Frozen Foods,Breakfast Foods,6278.50,2510.8892,3610.0
24,Food,Frozen Foods,Frozen Desserts,9329.26,3735.1895,4423.0
25,Food,Frozen Foods,Frozen Entrees,4183.06,1669.8595,1857.0
26,Food,Frozen Foods,Meat,4009.01,1620.4805,1651.0
27,Food,Frozen Foods,Pizza,4889.95,1955.7461,2525.0
28,Food,Frozen Foods,Vegetables,10365.33,4155.1374,4843.0
29,Food,Meat,Meat,2486.86,984.3473,1199.0
30,Food,Produce,Fruit,17863.05,7146.6596,8286.0
31,Food,Produce,Packaged Vegetables,1180.37,474.6871,559.0
32,Food,Produce,Specialty,6093.29,2443.0965,2928.0
33,Food,Produce,Vegetables,31777.87,12722.8269,14588.0
34,Food,Seafood,Seafood,2470.42,984.0403,1164.0
35,Food,Snack Foods,Snack Foods,47726.96,19115.3878,21491.0
36,Food,Snacks,Candy,10141.97,4056.9256,4822.0
37,Food,Starchy Foods,Starchy Foods,7790.06,3110.1617,3433.0
38,Non-Consumable,Carousel,Specialty,1300.86,523.1877,697.0
39,Non-Consumable,Checkout,Hardware,1245.99,506.7605,585.0
40,Non-Consumable,Checkout,Miscellaneous,1273.89,509.1281,620.0
41,Non-Consumable,Health and Hygiene,Bathroom Products,8549.83,3423.6980,4185.0
42,Non-Consumable,Health and Hygiene,Cold Remedies,2184.32,880.3907,1226.0
43,Non-Consumable,Health and Hygiene,Decongestants,2169.40,867.5591,1212.0
44,Non-Consumable,Health and Hygiene,Hygiene,4445.85,1784.4037,2579.0
45,Non-Consumable,Health and Hygiene,Pain Relievers,6511.23,2621.3690,2565.0
46,Non-Consumable,Household,Bathroom Products,853.97,340.2027,609.0
47,Non-Consumable,Household,Candles,986.08,400.4434,592.0
48,Non-Consumable,Household,Cleaning Supplies,4729.24,1907.0914,2309.0
49,Non-Consumable,Household,Electrical,11147.72,4477.1918,4703.0
50,Non-Consumable,Household,Hardware,2649.06,1059.2678,1197.0
51,Non-Consumable,Household,Kitchen Products,6823.04,2728.9778,2995.0
52,Non-Consumable,Household,Paper Products,10767.78,4304.3053,4876.0
53,Non-Consumable,Household,Plastic Products,4622.67,1825.9742,1808.0
54,Non-Consumable,Periodicals,Magazines,6207.53,2490.2450,2956.0

Media Analysis

In [58]:
media_analysis = data.groupby('media_type').agg(totalsales = pd.NamedAgg('store_sales(in millions)','sum'),
                               total_store_cost = pd.NamedAgg('store_cost(in millions)','sum'),
                               totalunits_sold = pd.NamedAgg('unit_sales(in millions)','sum'),
                               totalcost_aq = pd.NamedAgg('cost','sum')).reset_index()
media_analysis

,media_type,totalsales,total_store_cost,totalunits_sold,totalcost_aq
0,Bulk Mail,22599.97,9052.0785,10578.0,359831.33
1,Cash Register Handout,25678.49,10287.5261,12133.0,459972.46
2,Daily Paper,33573.71,13360.6404,15836.0,456733.30
3,"Daily Paper, Radio",44338.40,17780.0633,21074.0,668165.29
4,"Daily Paper, Radio, TV",34841.29,13914.5122,16515.0,479538.87
5,In-Store Coupon,29284.26,11735.0616,13908.0,449470.75
6,Product Attachment,35464.02,14189.5155,16669.0,560393.07
7,Radio,32913.11,13192.0477,15620.0,481584.72
8,Street Handout,33164.98,13288.6817,15759.0,550925.92
9,Sunday Paper,31590.02,12718.2007,14963.0,491880.03
10,"Sunday Paper, Radio",26617.51,10665.0638,12622.0,428032.88
11,"Sunday Paper, Radio, TV",21506.01,8622.9932,10170.0,304370.15
12,TV,23689.63,9482.3140,11067.0,307327.49

Store Level Analysis

In [59]:
data.groupby(['sales_country','store_type','store_state']).agg(totalsales = pd.NamedAgg('store_sales(in millions)','sum'),
                                                               total_store_cost = pd.NamedAgg('store_cost(in millions)','sum'),
                                                               totalunits_sold = pd.NamedAgg('unit_sales(in millions)','sum'),
                                                               totalcost_aq = pd.NamedAgg('cost','sum')).reset_index()

,sales_country,store_type,store_state,totalsales,total_store_cost,totalunits_sold,totalcost_aq
0,Canada,Deluxe Supermarket,BC,22427.00,8978.9983,10612.0,344414.38
1,Canada,Mid-Size Grocery,BC,3850.08,1544.4363,1822.0,56030.34
2,Mexico,Deluxe Supermarket,Yucatan,30318.51,12139.0264,14151.0,404143.02
3,Mexico,Deluxe Supermarket,Zacatecas,25908.44,10417.4739,12291.0,396288.65
4,Mexico,Gourmet Supermarket,Zacatecas,15489.19,6218.9857,7360.0,250292.32
5,Mexico,Mid-Size Grocery,DF,9307.09,3726.4683,4388.0,163136.42
6,Mexico,Mid-Size Grocery,Zacatecas,5806.18,2331.1224,2789.0,99954.64
7,Mexico,Small Grocery,Jalisco,1390.94,557.8254,717.0,46585.79
8,Mexico,Supermarket,Guerrero,10047.59,4024.4597,4749.0,147530.80
9,Mexico,Supermarket,Veracruz,17297.16,6962.3375,8226.0,262785.72
10,USA,Deluxe Supermarket,OR,35764.51,14341.8308,17060.0,462508.20
11,USA,Deluxe Supermarket,WA,37886.08,15197.6680,17877.0,561547.18
12,USA,Gourmet Supermarket,CA,27485.61,10990.1310,12920.0,420501.39
13,USA,Small Grocery,CA,2636.73,1054.5070,1269.0,82099.70
14,USA,Small Grocery,WA,2466.29,984.1527,1151.0,74619.21
15,USA,Supermarket,CA,26422.87,10572.3447,12452.0,400324.18
16,USA,Supermarket,OR,34675.61,13826.6497,16279.0,542351.59
17,USA,Supermarket,WA,86081.52,34420.2809,40801.0,1283112.73

Promotion Level Analysis